### ISSUE TITLE
add NOTPARALLEL option to add_check and add_memcheck

### ISSUE THREAD

**Issue by ecourreges-orange** [psycofdj/xtdmake#30]
Basically, I want my DB unit tests to run in -j1, while the rest of the tests run in -jN

https://stackoverflow.com/questions/17172310/make-disable-parallel-building-in-subdirectory-for-single-target-only

Thanks,
Kind Regards.

**Comment by psycofdj** [comment]
As far as I know, CMake doesn't allow a direct control of the GNU Makefile ```.NOTPARALLEL``` directive.

For ```add_check``` you can use the ```JOBS``` parameter. XTDMake generates a single target far all your unit-test in the module. In consequence, ```make -jN```  has no effect. This target actually call ctest which controls the parallel run using the ```JOBS``` parameter. 

Your problem is ```add_memcheck``` because it generates a separate target for each available unit-tests and therefore parallelism is under direct control of ```make -JN```. A possible solution would be the re-implement this using a single-target model that runs a wrapper that handle parallelism. **Pull requests are welcome**

From my point of view, a fine control on the parallelism is a bad solution to an underlying problem: all tests are distinct binaries and they **must** be able to run concurrently and the ```-jN``` should be only limited by hardware resources.

**Comment by ecourreges-orange** [comment]
Thank you for the insight, indeed, it might not be too hard to rework our unit tests that don't work in parallel, such as making them work with distinct databases.
